# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

trigger:
  branches:
    include:
    - master

pr:
- master

stages:
  - stage: Build_Images
    displayName: Build
          
    jobs:
    - job: Build
      strategy:
        matrix:
          mono606:
            monoVersionArg: 6.6=preview-xenial
            tagName: 6.6
          mono604:
            monoVersionArg: 6.4
            tagName: 6.4
          mono600:
            monoVersionArg: 6.0
            tagName: 6.0
          mono520:
            monoVersionArg: 5.20
            tagName: 5.20
          mono518:
            monoVersionArg: 5.18
            tagName: 5.18
          mono516:
            monoVersionArg: 5.16
            tagName: 5.16
          mono514:
            monoVersionArg: 5.14
            tagName: 5.14
          mono512:
            monoVersionArg: 5.12
            tagName: 5.12
          mono510:
            monoVersionArg: 5.10
            tagName: 5.10
          mono508:
            monoVersionArg: 5.8
            tagName: 5.8

      pool:
        vmImage: ubuntu-16.04

      steps:
      - checkout: self
        submodules: true
        fetchDepth: 1
      - bash: ./generate_images.sh -v $(monoVersionArg)
        displayName: Build Mono $(tagName)
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          containerRegistry: 'dockerhub'
          command: 'login'
      - task: Docker@2
        displayName: Push to Docker Hub
        inputs:
          containerRegistry: 'dockerhub'
          repository: 'radarr/testimages'
          command: 'push'
          tags: 'mono-$(tagName)'
        condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
